### ISSUE TITLE
Deployment issue

### ISSUE THREAD

**Issue by nysthee** [fizzed/stork#24]
Hi 
 When deploying I get the following error on my VSTS CI server:
`2018-07-25T20:35:17.4860494Z [ERROR] Unable to cleanly deploy
2018-07-25T20:35:17.4874552Z com.fizzed.blaze.ssh.SshException: Auth fail
2018-07-25T20:35:17.4890901Z 	at com.fizzed.blaze.ssh.impl.JschConnect.tryToUnwrap(JschConnect.java:369)
2018-07-25T20:35:17.4904381Z 	at com.fizzed.blaze.ssh.impl.JschConnect.doRun(JschConnect.java:356)
2018-07-25T20:35:17.4918699Z 	at com.fizzed.blaze.ssh.impl.JschConnect.doRun(JschConnect.java:50)
2018-07-25T20:35:17.4931760Z 	at com.fizzed.blaze.core.Action.runResult(Action.java:33)
2018-07-25T20:35:17.4944694Z 	at com.fizzed.blaze.core.Action.run(Action.java:39)
2018-07-25T20:35:17.4958020Z 	at com.fizzed.stork.deploy.Targets.sshConnect(Targets.java:71)
2018-07-25T20:35:17.4971056Z 	at com.fizzed.stork.deploy.Targets.connect(Targets.java:46)
2018-07-25T20:35:17.4984250Z 	at com.fizzed.stork.deploy.Deployer.deploy(Deployer.java:47)
2018-07-25T20:35:17.4997774Z 	at com.fizzed.stork.deploy.DeployMain.run(DeployMain.java:160)
2018-07-25T20:35:17.5010432Z 	at com.fizzed.stork.deploy.DeployMain.main(DeployMain.java:33)
2018-07-25T20:35:17.5023154Z Caused by: com.jcraft.jsch.JSchException: Auth fail
2018-07-25T20:35:17.5036770Z 	at com.jcraft.jsch.Session.connect(Session.java:519)
2018-07-25T20:35:17.5049415Z 	at com.fizzed.blaze.ssh.impl.JschConnect.doRun(JschConnect.java:342)
2018-07-25T20:35:17.5062275Z 	... 8 common frames omitted`

What can the issue be? I can scp files to the server, so SSH is configured correctly.

**Comment by jjlauer** [comment]
Command-line scp vs. JSCH (the pure java library) that Stork relies on are
close, but not the same.  For example, if you rely on an ssh-agent to make
auth work via command-line ssh tools, then jsch probably will auth fail.
There are other exotic setups that can cause it too such as bastion hosts,
proxying, etc.

What does your ssh authentication setup look like?

**Comment by nysthee** [comment]
Hi thanks for the swift response! I really appreciate this.

I believe indeed VSTS is using an ssh-agent.
The weird thing is from my local machine this works. I am also using ssh-agent there.

What is the preferred ssh setup?

**Comment by nysthee** [comment]
Hi @jjlauer 

Is there any additional information required? Thanks for the response!

**Comment by nysthee** [comment]
This is solved. Problem was a non default location of ssh keys.
